UPDATE SCOTT.T_A_BOOK_TYPE SET NAME = '学习类', ORDER_NO = 1 WHERE ID = 4;
UPDATE SCOTT.T_A_BOOK_TYPE SET NAME = '编程类', ORDER_NO = 2 WHERE ID = 5;
UPDATE SCOTT.T_A_BOOK_TYPE SET NAME = '冒险类', ORDER_NO = 3 WHERE ID = 6;