UPDATE SCOTT.T_BOOK SET AUTHOR = 'AAA', DANJIA = 5.00, NAME = '学习', NUM = 10, BOOK_TYPE_ID = 4 WHERE ID = 1;
UPDATE SCOTT.T_BOOK SET AUTHOR = 'BBB', DANJIA = 8.00, NAME = '编程', NUM = 12, BOOK_TYPE_ID = 5 WHERE ID = 2;
UPDATE SCOTT.T_BOOK SET AUTHOR = 'CCC', DANJIA = 10.00, NAME = '冒险', NUM = 20, BOOK_TYPE_ID = 6 WHERE ID = 3;